spring.application.name=spring-security-test
server.port=8081
gs=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
spring.security.oauth2.client.registration.google.client-id=177705995404-kj4gfsm92sbcot52gvqdsqa67vsksrir.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${gs}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
